### ISSUE TITLE
Can't open Lineage2 c1 maps

### ISSUE THREAD

**Issue by karaxuna** [bunnytrack/UTPackage.js#2]
When trying to open a map (eg. `./MAPS/18_14.unr`), I was getting invalid signature error. I figured out that it was encrypted and used [L2Crypt](https://github.com/acmi/L2crypt/blob/master/src/main/java/acmi/l2/clientmod/crypt/L2Crypt.java) to decrypt them. Worked well for many files, but not for maps. The error I'm getting is:

```
UTPackage.js?v=1630170369:1717 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at window.UTReader.getObjectProperties (UTPackage.js?v=1630170369:1717:26)
    at window.UTReader.getLevelSummary (UTPackage.js?v=1630170369:2422:30)
    at showLevelSummary ((index):423:35)
    at fileReader.onload ((index):371:11)
```

It happens here:

```javascript
let currentPropName = reader.nameTable[reader.getCompactIndex()]; // reader.getCompactIndex() returns negative number

while (currentPropName.toLowerCase() !== "none") { // throws error because currentPropName is undefined
```

Here's decrypted map [file](https://easyupload.io/5ayjse).

**Comment by sapphire-bt** [comment]
Hi there.

I'm unfamiliar with Lineage II but can see on Wikipedia that it uses "Unreal Engine 2.5" - unfortunately I've only tested this script on Unreal Engine 1 games.

When you say it worked well for many files, were they textures/sounds/etc? If so, I would guess that some file types didn't change much between engine versions, which might be why the script was still able to read them.

**Comment by karaxuna** [comment]
@sapphire-bt yes, sounds worked perfectly, for maps - imports/exports tables also work correctly I think. I would not ask you, but I spent hours without luck to solve it, maybe it's a very small issue for somebody who knows codebase very well. Could you please see if there's a quick fix for this issue?

**Comment by sapphire-bt** [comment]
@karaxuna I've taken a look just now and it seems that there's a PointRegion object in the map which has an extra 4 bytes compared to Unreal Engine 1 - that will be what's messing up the file reader offset and causing the error.

To get the script working in the meantime you can edit the [PointRegion class](https://github.com/bunnytrack/UTPackage.js/blob/master/UTReader.js#L291) with this dirty hack:

```js
class PointRegion {
	constructor() {
		this.zone        = reader.getCompactIndex();
		this.i_leaf      = reader.getUint32();
		reader.getUint32(); // skip over the extra 4 bytes
		this.zone_number = reader.getUint8();
	}
}
```

This stops the script from throwing an error while parsing the map, but when I try to view the models/brushes I get a different error, so we're kind of back to square one as it's likely there are more structural changes that would need to be accounted for.

Just FYI if your aim is to view the models/brushes then this might all be a moot point anyway: according to the export table there are only a few brushes contained within the file, meaning they've _probably_ been deleted - which wouldn't be surprising if the file was encrypted to begin with.

**Comment by karaxuna** [comment]
@sapphire-bt ok, huge thanks for help anyway!
